const onChannelCreate = require('./functions/onChannelCreate');
const onChannelDelete = require('./functions/onChannelDelete');
const onChannelPinsUpdate = require('./functions/onChannelPinsUpdate');
const onChannelUpdate = require('./functions/onChannelUpdate');
const onClientUserGuildSettingsUpdate = require('./functions/onClientUserGuildSettingsUpdate');
const onClientUserSettingsUpdate = require('./functions/onClientUserSettingsUpdate');
const onDebug = require('./functions/onDebug');
const onDisconnect = require('./functions/onDisconnect');
const onEmojiCreate = require('./functions/onEmojiCreate');
const onEmojiDelete = require('./functions/onEmojiDelete');
const onEmojiUpdate = require('./functions/onEmojiUpdate');
const onError = require('./functions/onError');
const onGuildBanAdd = require('./functions/onGuildBanAdd');
const onGuildBanRemove = require('./functions/onGuildBanRemove');
const onGuildCreate = require('./functions/onGuildCreate');
const onGuildDelete = require('./functions/onGuildDelete');
const onGuildMemberAdd = require('./functions/onGuildMemberAdd');
const onGuildMemberAvailable = require('./functions/onGuildMemberAvailable');
const onGuildMemberRemove = require('./functions/onGuildMemberRemove');
const onGuildMembersChunk = require('./functions/onGuildMembersChunk');
const onGuildMemberSpeaking = require('./functions/onGuildMemberSpeaking');
const onGuildMemberUpdate = require('./functions/onGuildMemberUpdate');
const onGuildUnavailable = require('./functions/onGuildUnavailable');
const onGuildUpdate = require('./functions/onGuildUpdate');
const onMessage = require('./functions/onMessage');
const onMessageDelete = require('./functions/onMessageDelete');
const onMessageDeleteBulk = require('./functions/onMessageDeleteBulk');
const onMessageReactionAdd = require('./functions/onMessageReactionAdd');
const onMessageReactionRemove = require('./functions/onMessageReactionRemove');
const onMessageReactionRemoveAll = require('./functions/onMessageReactionRemoveAll');
const onMessageUpdate = require('./functions/onMessageUpdate');
const onPresenceUpdate = require('./functions/onPresenceUpdate');
const onReady = require('./functions/onReady');
const onReconnecting = require('./functions/onReconnecting');
const onResume = require('./functions/onResume');
const onRoleCreate = require('./functions/onRoleCreate');
const onRoleDelete = require('./functions/onRoleDelete');
const onRoleUpdate = require('./functions/onRoleUpdate');
const onTypingStart = require('./functions/onTypingStart');
const onTypingStop = require('./functions/onTypingStop');
const onUserNoteUpdate = require('./functions/onUserNoteUpdate');
const onUserUpdate = require('./functions/onUserUpdate');
const onVoiceStateUpdate = require('./functions/onVoiceStateUpdate');
const onWarn = require('./functions/onWarn');


module.exports = {
    channelCreate: (channel) => onChannelCreate(channel),
    channelDelete: (channel) => onChannelDelete(channel),
    channelPinsUpdate: (channel, time) => onChannelPinsUpdate(channelUpdate, time),
    channelUpdate: (oldChannel, newChannel) => onChannelUpdate(oldChannel, newChannel),
    clientUserGuildSettingsUpdate: (clientUserGuildSettings) => onClientUserGuildSettingsUpdate(clientUserGuildSettings),
    clientUserSettingsUpdate: (clientUserSettings) => onClientUserSettingsUpdate(clientUserSettings),
    debug: (info) => onDebug(info),
    disconnect: (erMsg, code) => onDisconnect(erMsg, code),
    emojiCreate: (emoji) => onEmojiCreate(emoji),
    emojiDelete: (emoji) => onEmojiDelete(emoji),
    emojiUpdate: (oldEmoji, newEmoji) => onEmojiUpdate(oldEmoji, newEmoji),
    error: (error) => onError(error),
    guildBanAdd: (guild, user) => onGuildBanAdd(guild, user),
    guildBanRemove: (guild, user) => onGuildBanRemove(guild, user),
    guildCreate: (guild) => onGuildCreate(guild),
    guildDelete: (guild) => onGuildDelete(guild),
    guildMemberAdd: (member) => onGuildMemberAdd(member),
    guildMemberAvailable: (member) => onGuildMemberAvailable(member),
    guildMemberRemove: (member) => onGuildMemberRemove(member),
    guildMembersChunk: (members, guild) => onGuildMembersChunk(members, guild),
    guildMemberSpeaking: (member, speaking) => onGuildMemberSpeaking(member, speaking),
    guildMemberUpdate: (oldMember, newMember) => onGuildMemberUpdate(oldMember, newMember),
    guildUnavailable: (guild) => onGuildUnavailable(guild),
    guildUpdate: (oldGuild, newGuild) => onGuildUpdate(oldGuild, newGuild),
    message: (message) => onMessage(message),
    messageDelete: (message) => onMessageDelete(message),
    messageDeleteBulk: (messages) => onMessageDeleteBulk(messages),
    messageReactionAdd: (messageReaction, user) => onMessageReactionAdd(messageReaction, user),
    messageReactionRemove: (messageReaction, user) => onMessageReactionRemove(messageReaction, user),
    messageReactionRemoveAll: (message) => onMessageReactionRemoveAll(message),
    messageUpdate: (oldMessage, newMessage) => onMessageUpdate(oldMessage, newMessage),
    presenceUpdate: (oldMember, newMember) => onPresenceUpdate(oldMember, newMember),
    ready: () => onReady(),
    reconnecting: () => onReconnecting(),
    resume: (replayed) => onResume(replayed),
    roleCreate: (role) => onRoleCreate(role),
    roleDelete: (role) => onRoleDelete(role),
    roleUpdate: (oldRole, newRole) => onRoleUpdate(oldRole, newRole),
    typingStart: (channel, user) => onTypingStart(channel, user),
    typingStop: (channel, user) => onTypingStop(channel, user),
    userNoteUpdate: (user, oldNote, newNote) => onUserNoteUpdate(user, oldNote, newNote),
    userUpdate: (oldUser, newUser) => onUserUpdate(oldUser, newUser),
    voiceStateUpdate: (oldMember, newMember) => onVoiceStateUpdate(oldMember, newMember),
    warn: (info) => onWarn(info)
};
