const onChannelCreate = require('./functions/channel/create/onChannelCreate');
const onChannelDelete = require('./functions/channel/delete/onChannelDelete');
const onChannelPinsUpdate = require('./functions/channel/pins/update/onChannelPinsUpdate');
const onChannelUpdate = require('./functions/channel/update/onChannelUpdate');
const onClientUserGuildSettingsUpdate = require('./functions/client/user/guild/setting/update/onClientUserGuildSettingsUpdate');
const onClientUserSettingsUpdate = require('./functions/client/user/setting/update/onClientUserSettingsUpdate');
const onDebug = require('./functions/debug/onDebug');
const onDisconnect = require('./functions/disconnect/onDisconnect');
const onEmojiCreate = require('./functions/emoji/create/onEmojiCreate');
const onEmojiDelete = require('./functions/emoji/delete/onEmojiDelete');
const onEmojiUpdate = require('./functions/emoji/update/onEmojiUpdate');
const onError = require('./functions/error/onError');
const onGuildBanAdd = require('./functions/guild/ban/add/onGuildBanAdd');
const onGuildBanRemove = require('./functions/guild/ban/remove/onGuildBanRemove');
const onGuildCreate = require('./functions/guild/create/onGuildCreate');
const onGuildDelete = require('./functions/guild/delete/onGuildDelete');
const onGuildMemberAdd = require('./functions/guild/member/add/onGuildMemberAdd');
const onGuildMemberAvailable = require('./functions/guild/member/available/onGuildMemberAvailable');
const onGuildMemberRemove = require('./functions/guild/member/remove/onGuildMemberRemove');
const onGuildMembersChunk = require('./functions/guild/member/chunk/onGuildMembersChunk');
const onGuildMemberSpeaking = require('./functions/guild/member/speaking/onGuildMemberSpeaking');
const onGuildMemberUpdate = require('./functions/guild/member/update/onGuildMemberUpdate');
const onGuildUnavailable = require('./functions/guild/unavailable/onGuildUnavailable');
const onGuildUpdate = require('./functions/guild/update/onGuildUpdate');
const onMessage = require('./functions/message/onMessage');
const onMessageDelete = require('./functions/message/delete/onMessageDelete');
const onMessageDeleteBulk = require('./functions/message/delete/bulk/onMessageDeleteBulk');
const onMessageReactionAdd = require('./functions/message/reaction/add/onMessageReactionAdd');
const onMessageReactionRemove = require('./functions/message/reaction/remove/onMessageReactionRemove');
const onMessageReactionRemoveAll = require('./functions/message/reaction/remove/all/onMessageReactionRemoveAll');
const onMessageUpdate = require('./functions/message/update/onMessageUpdate');
const onPresenceUpdate = require('./functions/presence/update/onPresenceUpdate');
const onReady = require('./functions/ready/onReady');
const onReconnecting = require('./functions/reconnecting/onReconnecting');
const onResume = require('./functions/resume/onResume');
const onRoleCreate = require('./functions/role/create/onRoleCreate');
const onRoleDelete = require('./functions/role/delete/onRoleDelete');
const onRoleUpdate = require('./functions/role/update/onRoleUpdate');
const onTypingStart = require('./functions/typing/start/onTypingStart');
const onTypingStop = require('./functions/typing/stop/onTypingStop');
const onUserNoteUpdate = require('./functions/user/note/update/onUserNoteUpdate');
const onUserUpdate = require('./functions/user/update/onUserUpdate');
const onVoiceStateUpdate = require('./functions/voice/state/update/onVoiceStateUpdate');
const onWarn = require('./functions/warn/onWarn');


module.exports = {
    channelCreate: (channel) => onChannelCreate(channel),
    channelDelete: (channel) => onChannelDelete(channel),
    channelPinsUpdate: (channel, time) => onChannelPinsUpdate(channelUpdate, time),
    channelUpdate: (oldChannel, newChannel) => onChannelUpdate(oldChannel, newChannel),
    clientUserGuildSettingsUpdate: (clientUserGuildSettings) => onClientUserGuildSettingsUpdate(clientUserGuildSettings),
    clientUserSettingsUpdate: (clientUserSettings) => onClientUserSettingsUpdate(clientUserSettings),
    debug: (info) => onDebug(info),
    disconnect: (erMsg, code) => onDisconnect(erMsg, code),
    emojiCreate: (emoji) => onEmojiCreate(emoji),
    emojiDelete: (emoji) => onEmojiDelete(emoji),
    emojiUpdate: (oldEmoji, newEmoji) => onEmojiUpdate(oldEmoji, newEmoji),
    error: (error) => onError(error),
    guildBanAdd: (guild, user) => onGuildBanAdd(guild, user),
    guildBanRemove: (guild, user) => onGuildBanRemove(guild, user),
    guildCreate: (guild) => onGuildCreate(guild),
    guildDelete: (guild) => onGuildDelete(guild),
    guildMemberAdd: (member) => onGuildMemberAdd(member),
    guildMemberAvailable: (member) => onGuildMemberAvailable(member),
    guildMemberRemove: (member) => onGuildMemberRemove(member),
    guildMembersChunk: (members, guild) => onGuildMembersChunk(members, guild),
    guildMemberSpeaking: (member, speaking) => onGuildMemberSpeaking(member, speaking),
    guildMemberUpdate: (oldMember, newMember) => onGuildMemberUpdate(oldMember, newMember),
    guildUnavailable: (guild) => onGuildUnavailable(guild),
    guildUpdate: (oldGuild, newGuild) => onGuildUpdate(oldGuild, newGuild),
    message: (message) => onMessage(message),
    messageDelete: (message) => onMessageDelete(message),
    messageDeleteBulk: (messages) => onMessageDeleteBulk(messages),
    messageReactionAdd: (messageReaction, user) => onMessageReactionAdd(messageReaction, user),
    messageReactionRemove: (messageReaction, user) => onMessageReactionRemove(messageReaction, user),
    messageReactionRemoveAll: (message) => onMessageReactionRemoveAll(message),
    messageUpdate: (oldMessage, newMessage) => onMessageUpdate(oldMessage, newMessage),
    presenceUpdate: (oldMember, newMember) => onPresenceUpdate(oldMember, newMember),
    ready: () => onReady(),
    reconnecting: () => onReconnecting(),
    resume: (replayed) => onResume(replayed),
    roleCreate: (role) => onRoleCreate(role),
    roleDelete: (role) => onRoleDelete(role),
    roleUpdate: (oldRole, newRole) => onRoleUpdate(oldRole, newRole),
    typingStart: (channel, user) => onTypingStart(channel, user),
    typingStop: (channel, user) => onTypingStop(channel, user),
    userNoteUpdate: (user, oldNote, newNote) => onUserNoteUpdate(user, oldNote, newNote),
    userUpdate: (oldUser, newUser) => onUserUpdate(oldUser, newUser),
    voiceStateUpdate: (oldMember, newMember) => onVoiceStateUpdate(oldMember, newMember),
    warn: (info) => onWarn(info)
};
